# Generated by Django 3.1.3 on 2022-01-05 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='cateogry',
        ),
        migrations.AddField(
            model_name='shop',
            name='category_name',
            field=models.CharField(default='기타', max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ShopCategory',
        ),
    ]
