# Generated by Django 3.1.3 on 2022-01-23 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0004_alter_shop_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
