# Generated by Django 3.2 on 2022-01-07 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, verbose_name='메인카테고리')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='메인카테고리 등록날짜')),
                ('updated', models.DateField(auto_now=True, verbose_name='메인카테고리 업데이트날짜')),
            ],
            options={
                'verbose_name_plural': '메인카테고리 목록',
                'db_table': 'maincategories',
            },
        ),
        migrations.CreateModel(
            name='Merchandise',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('common_code', models.CharField(max_length=8, verbose_name='상품 공통코드')),
                ('full_code', models.CharField(max_length=12, unique=True, verbose_name='상품 전체코드')),
                ('name', models.CharField(max_length=20, verbose_name='상품명')),
                ('color', models.CharField(max_length=20, verbose_name='상품 색상')),
                ('size', models.CharField(choices=[('FREE', 'FREE'), ('SMALL', 'S'), ('MEDIUM', 'M'), ('LARGE', 'L'), ('XLARGE', 'XL')], max_length=6, verbose_name='상품 사이즈')),
                ('current_stock', models.PositiveIntegerField(default=0, verbose_name='상품 현재재고')),
                ('safety_stock', models.PositiveIntegerField(default=0, verbose_name='상품 안전재고')),
                ('soldout_state', models.CharField(choices=[('IN', 'INSTOCK'), ('TEM', 'TEMPORARY_SOLDOUT'), ('PER', 'PERMANANT_SOLDOUT')], max_length=3, verbose_name='상품 품절상태')),
                ('on_sale', models.BooleanField(default=True, verbose_name='상품 판매')),
                ('on_display', models.BooleanField(default=True, verbose_name='상품 전시')),
                ('standard_price', models.PositiveIntegerField(default=0, verbose_name='상품 정가')),
                ('discounted_price', models.PositiveIntegerField(default=0, verbose_name='상품 할인금액')),
                ('main_img', models.TextField(blank=True, null=True, verbose_name='상품 메인이미지')),
                ('sub_img_0', models.TextField(blank=True, null=True, verbose_name='상품 서브이미지0')),
                ('sub_img_1', models.TextField(blank=True, null=True, verbose_name='상품 서브이미지1')),
                ('sub_img_2', models.TextField(blank=True, null=True, verbose_name='상품 서브이미지2')),
                ('description', models.TextField(blank=True, null=True, verbose_name='상품 설명')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='상품 등록날짜')),
                ('updated', models.DateField(auto_now=True, verbose_name='상품 업데이트날짜')),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='셀러')),
            ],
            options={
                'verbose_name_plural': '상품 목록',
                'db_table': 'merchandises',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, verbose_name='서브카테고리')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='서브카테고리 등록날짜')),
                ('updated', models.DateField(auto_now=True, verbose_name='서브카테고리 업데이트날짜')),
                ('maincategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.maincategory', verbose_name='메인카테고리')),
            ],
            options={
                'verbose_name_plural': '서브카테고리 목록',
                'db_table': 'subcategories',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20, verbose_name='상품문의 제목')),
                ('content', models.CharField(max_length=255, verbose_name='상품문의 내용')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='상품문의 등록날짜')),
                ('updated', models.DateField(auto_now=True, verbose_name='상품문의 업데이트날짜')),
                ('merchandise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.merchandise', verbose_name='상품')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='유저')),
            ],
            options={
                'verbose_name_plural': '상품문의 목록',
                'db_table': 'questions',
            },
        ),
        migrations.AddField(
            model_name='merchandise',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.subcategory', verbose_name='서브카테고리'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=255, verbose_name='상품답변 내용')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='상품답변 등록날짜')),
                ('updated', models.DateField(auto_now=True, verbose_name='상품답변 업데이트날짜')),
                ('merchandise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.merchandise', verbose_name='상품')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.question', verbose_name='상품문의')),
            ],
            options={
                'verbose_name_plural': '상품답변 목록',
                'db_table': 'comments',
            },
        ),
    ]
