# Generated by Django 3.2 on 2022-01-07 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchandise',
            name='main_img',
            field=models.URLField(blank=True, null=True, verbose_name='상품 메인이미지'),
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='sub_img_0',
            field=models.URLField(blank=True, null=True, verbose_name='상품 서브이미지0'),
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='sub_img_1',
            field=models.URLField(blank=True, null=True, verbose_name='상품 서브이미지1'),
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='sub_img_2',
            field=models.URLField(blank=True, null=True, verbose_name='상품 서브이미지2'),
        ),
    ]
