# Generated by Django 4.0.1 on 2022-01-08 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('shop_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('shop_name', models.CharField(max_length=20)),
            ],
        ),
    ]
