# Generated by Django 3.2.9 on 2022-02-02 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('local_account', '0002_seller'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='seller',
            table='seller',
        ),
    ]
