# Generated by Django 3.2.9 on 2022-02-03 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_account', '0004_alter_seller_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='seller',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Seller',
        ),
    ]
