# Generated by Django 4.0.1 on 2022-01-13 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Board",
            fields=[
                # ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ("title", models.CharField(max_length=20)),
                ("content", models.TextField()),
                ("writer", models.CharField(max_length=20)),
            ],
            options={
                "db_table": "board",
                "managed": False,
            },
        ),
    ]
