# Generated by Django 4.0.1 on 2022-02-02 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
        ('users', '0004_refreshstorage_user_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='market_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='market.market'),
        ),
        migrations.AddField(
            model_name='user',
            name='market_yn',
            field=models.BooleanField(default=False),
        ),
    ]
