# Generated by Django 3.2 on 2022-01-15 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_seller',
        ),
    ]
