# Generated by Django 3.2.11 on 2022-01-08 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('idx', models.AutoField(db_column='Idx', primary_key=True, serialize=False)),
                ('email', models.CharField(db_column='Email', max_length=30, unique=True)),
                ('password', models.CharField(db_column='Password', max_length=20)),
                ('name', models.CharField(db_column='Name', max_length=20)),
                ('is_staff', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'User',
                'managed': False,
            },
        ),
    ]
