# Generated by Django 4.0.1 on 2022-01-14 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id_item', models.CharField(db_column='id_Item', max_length=5, primary_key=True, serialize=False)),
                ('color', models.CharField(blank=True, max_length=45, null=True)),
                ('size', models.CharField(blank=True, max_length=45, null=True)),
                ('photo', models.TextField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('stock', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Item',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id_store', models.CharField(db_column='id_Store', max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('detail', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'Store',
                'managed': False,
            },
        ),
    ]
