# Generated by Django 4.0.1 on 2022-02-11 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='board_name',
        ),
        migrations.RemoveField(
            model_name='board',
            name='contents',
        ),
        migrations.RemoveField(
            model_name='board',
            name='hits',
        ),
        migrations.RemoveField(
            model_name='board',
            name='write_dt',
        ),
        migrations.AddField(
            model_name='board',
            name='content',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='board',
            name='title',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='writer',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterModelTable(
            name='board',
            table=None,
        ),
    ]
