# Generated by Django 4.0.1 on 2022-02-11 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_remove_board_board_name_remove_board_contents_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='board',
            table='board',
        ),
    ]
