# Generated by Django 4.0.1 on 2022-02-11 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_alter_board_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Board',
        ),
    ]
