# Generated by Django 4.0.1 on 2022-02-11 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_remove_board_writer_board_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Board',
        ),
    ]
