# Generated by Django 2.1.15 on 2022-01-07 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('brand_name', models.CharField(
                    max_length=20, primary_key=True, serialize=False)),
                ('brand_code', models.CharField(
                    blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'brand',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sangpum',
            fields=[
                # ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obj_name', models.CharField(max_length=14)),
                ('obj_color', models.CharField(max_length=14)),
                ('obj_size', models.CharField(max_length=4)),
                ('brand_code', models.CharField(
                    blank=True, max_length=20, null=True)),
                ('price', models.CharField(blank=True, max_length=20, null=True)),
                ('discount_price', models.CharField(
                    blank=True, max_length=20, null=True)),
                ('obj_code', models.CharField(blank=True, max_length=4, null=True)),
            ],
            options={
                'db_table': 'object',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('type_code', models.CharField(
                    max_length=4, primary_key=True, serialize=False)),
                ('type_name', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=20,
                 primary_key=True, serialize=False)),
                ('pw', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(blank=True, max_length=10, null=True)),
                ('id_num', models.CharField(blank=True, max_length=14, null=True)),
                ('phone', models.CharField(blank=True, max_length=14, null=True)),
                # ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=30, null=True)),
                # ('zipcode', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
