# Generated by Django 4.0.1 on 2022-01-08 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sangpum',
            table='sangpum',
        ),
    ]
