# Generated by Django 4.0.1 on 2022-01-09 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_board'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Board',
        ),
    ]
