# Generated by Django 3.2 on 2022-01-06 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mutbly', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantity',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quantities', to='mutbly.item'),
        ),
    ]
