# Generated by Django 3.2 on 2022-01-08 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mutbly', '0005_quantity_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantity',
            name='size',
            field=models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], default='XS', max_length=2),
        ),
    ]
