# Generated by Django 4.0.1 on 2022-01-16 10:56

from django.db import migrations
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', user.models.MyManager()),
            ],
        ),
    ]
