# Generated by Django 4.0.1 on 2022-02-03 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('price', models.IntegerField()),
                ('sale_price', models.IntegerField()),
                ('description', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='img/')),
                ('image_detail', models.ImageField(null=True, upload_to='img/')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_date', models.DateTimeField(auto_now=True, verbose_name='삭제 날짜')),
                ('is_hidden', models.BooleanField(default=False)),
                ('is_sold_out', models.BooleanField(default=False)),
                ('hit_count', models.IntegerField(default=0, verbose_name='조회수')),
                ('like_count', models.IntegerField(default=0, verbose_name='좋아요수')),
                ('reg_date', models.DateTimeField(auto_now=True, verbose_name='등록일')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='등록일')),
                ('quantity', models.IntegerField(default=0)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendors.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='ProductOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_date', models.DateTimeField(auto_now=True, verbose_name='등록일')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='등록일')),
                ('option1_type', models.CharField(max_length=128, verbose_name='옵션1 유형')),
                ('option1_name', models.CharField(max_length=128, verbose_name='옵션1 이름')),
                ('option1_price', models.IntegerField(default=0, verbose_name='옵션1 추가가격')),
                ('option1_stock', models.IntegerField(verbose_name='옵션1 재고수량')),
                ('option2_type', models.CharField(default=None, max_length=128, null=True, verbose_name='옵션2 유형')),
                ('option2_name', models.CharField(default=None, max_length=128, null=True, verbose_name='옵션2 유형')),
                ('option2_price', models.IntegerField(default=None, null=True, verbose_name='옵션2 추가가격')),
                ('option2_stock', models.IntegerField(default=None, null=True, verbose_name='옵션2 재고수량')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
