# Generated by Django 4.0.1 on 2022-01-20 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_category_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productoption',
            unique_together={('product', 'color', 'size')},
        ),
    ]
