# Generated by Django 4.0.1 on 2022-01-16 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_cart'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cart',
            table='carts',
        ),
    ]
