# Generated by Django 4.0.1 on 2022-01-21 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_rename_cart_cartitem_alter_cartitem_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItemList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('main_image_url', models.URLField(max_length=2000)),
                ('color', models.CharField(max_length=10)),
                ('size', models.CharField(max_length=5)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('extra_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('quantity', models.PositiveSmallIntegerField()),
                ('is_sold_out', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'cart_item_lists',
                'managed': False,
            },
        ),
    ]
