# Generated by Django 4.0.1 on 2022-02-04 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_producthistory_discount_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_image_url',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image_url',
            field=models.CharField(max_length=2000),
        ),
    ]
