# Generated by Django 4.0.1 on 2022-01-15 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
                ('size', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'product',
                'managed': False,
            },
        ),
    ]
