# Generated by Django 4.0.1 on 2022-02-13 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_alter_market_site_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='날짜')),
                ('sales', models.PositiveIntegerField(default=0, verbose_name='일일 매출')),
                ('sale_number', models.PositiveIntegerField(default=0, verbose_name='일일 판매 개수')),
            ],
        ),
    ]
