# Generated by Django 4.0.1 on 2022-01-09 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mutbly', '0002_alter_product_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='static/photos'),
        ),
        migrations.AlterModelTable(
            name='product',
            table='mutbly_product',
        ),
        migrations.AlterModelTable(
            name='user',
            table='mutbly_user',
        ),
    ]
