# Generated by Django 4.0.1 on 2022-01-08 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clothes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('options', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upper',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upper', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='upper',
            name='size_upper',
            field=models.ManyToManyField(blank=True, related_name='upper', to='options.size_upper', verbose_name='사이즈'),
        ),
        migrations.AddField(
            model_name='outers_photo',
            name='clothes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outers_photos', to='clothes.outers', verbose_name='상품명'),
        ),
        migrations.AddField(
            model_name='outers',
            name='colors',
            field=models.ManyToManyField(blank=True, related_name='outers', to='options.Color', verbose_name='색상'),
        ),
        migrations.AddField(
            model_name='outers',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='outers',
            name='size_outer',
            field=models.ManyToManyField(blank=True, related_name='outers', to='options.size_outer', verbose_name='사이즈'),
        ),
        migrations.AddField(
            model_name='onepieces_photo',
            name='clothes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onepieces_photos', to='clothes.onepieces', verbose_name='상품명'),
        ),
        migrations.AddField(
            model_name='onepieces',
            name='colors',
            field=models.ManyToManyField(blank=True, related_name='onepieces', to='options.Color', verbose_name='색상'),
        ),
        migrations.AddField(
            model_name='onepieces',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onepieces', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='onepieces',
            name='size_onepiece',
            field=models.ManyToManyField(blank=True, related_name='onepieces', to='options.size_onepiece', verbose_name='사이즈'),
        ),
    ]
