# Generated by Django 3.2.9 on 2022-01-07 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register', models.DateField(auto_created=True, null=True)),
                ('product_name', models.CharField(max_length=200, null=True)),
                ('price', models.IntegerField()),
                ('size', models.TextField(null=True)),
                ('count', models.IntegerField()),
                ('description', models.TextField(max_length=200)),
                ('image', models.ImageField(upload_to='article/')),
                ('seller', models.TextField(null=True)),
            ],
        ),
    ]
