# Generated by Django 3.2.9 on 2022-01-07 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='register',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
