# Generated by Django 3.2.9 on 2022-01-07 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='register',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='seller',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
