# Generated by Django 4.0.1 on 2022-01-08 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('options', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Onepieces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='상품명')),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField(verbose_name='가격')),
            ],
            options={
                'verbose_name_plural': '원피스',
            },
        ),
        migrations.CreateModel(
            name='Onepieces_photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('file', models.ImageField(upload_to='onepiece')),
            ],
            options={
                'verbose_name_plural': '원피스 사진',
            },
        ),
        migrations.CreateModel(
            name='Outers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='상품명')),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField(verbose_name='가격')),
            ],
            options={
                'verbose_name_plural': '아우터',
            },
        ),
        migrations.CreateModel(
            name='Outers_photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('file', models.ImageField(upload_to='outer')),
            ],
            options={
                'verbose_name_plural': '아우터 사진',
            },
        ),
        migrations.CreateModel(
            name='Upper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='상품명')),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField(verbose_name='가격')),
                ('colors', models.ManyToManyField(blank=True, related_name='upper', to='options.Color', verbose_name='색상')),
            ],
            options={
                'verbose_name_plural': '상의',
            },
        ),
        migrations.CreateModel(
            name='Uppers_photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('file', models.ImageField(upload_to='upper')),
                ('clothes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upper_photos', to='clothes.upper', verbose_name='상품명')),
            ],
            options={
                'verbose_name_plural': '상의사진',
            },
        ),
    ]
