# Generated by Django 4.0.1 on 2022-01-09 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clothes', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upper_comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('Author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upper_comments', to=settings.AUTH_USER_MODEL)),
                ('upper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upper_comments', to='clothes.upper')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Outer_comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('Author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outer_comments', to=settings.AUTH_USER_MODEL)),
                ('outer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outer_comments', to='clothes.outers')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Onepiece_comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('Author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onepiece_comments', to=settings.AUTH_USER_MODEL)),
                ('onepiece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onepiece_comments', to='clothes.onepieces')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
