# Generated by Django 4.0.1 on 2022-01-09 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0003_upper_comment_outer_comment_onepiece_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='onepiece_comment',
            options={'verbose_name_plural': '원피스 질문'},
        ),
        migrations.AlterModelOptions(
            name='outer_comment',
            options={'verbose_name_plural': '아우터 질문'},
        ),
        migrations.AlterModelOptions(
            name='upper_comment',
            options={'verbose_name_plural': '상의 질문'},
        ),
    ]
