# Generated by Django 3.2.11 on 2022-01-08 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Markets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', models.IntegerField(blank=True, db_column='Idx', null=True)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=30, null=True)),
            ],
            options={
                'db_table': 'Markets',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Onepiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', models.IntegerField(blank=True, db_column='Idx', null=True)),
                ('prodname', models.CharField(blank=True, db_column='ProdName', max_length=20, null=True)),
                ('price', models.IntegerField(blank=True, db_column='Price', null=True)),
                ('image', models.CharField(blank=True, db_column='Image', max_length=20, null=True)),
                ('marketidx', models.IntegerField(blank=True, db_column='MarketIdx', null=True)),
            ],
            options={
                'db_table': 'OnePiece',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Outwear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', models.IntegerField(blank=True, db_column='Idx', null=True)),
                ('prodname', models.CharField(blank=True, db_column='ProdName', max_length=20, null=True)),
                ('price', models.IntegerField(blank=True, db_column='Price', null=True)),
                ('image', models.CharField(blank=True, db_column='Image', max_length=20, null=True)),
                ('marketidx', models.IntegerField(blank=True, db_column='MarketIdx', null=True)),
            ],
            options={
                'db_table': 'Outwear',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', models.IntegerField(blank=True, db_column='Idx', null=True)),
                ('prodname', models.CharField(blank=True, db_column='ProdName', max_length=20, null=True)),
                ('price', models.IntegerField(blank=True, db_column='Price', null=True)),
                ('image', models.CharField(blank=True, db_column='Image', max_length=20, null=True)),
                ('marketidx', models.IntegerField(blank=True, db_column='MarketIdx', null=True)),
            ],
            options={
                'db_table': 'Pants',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Skirt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', models.IntegerField(blank=True, db_column='Idx', null=True)),
                ('prodname', models.CharField(blank=True, db_column='ProdName', max_length=20, null=True)),
                ('price', models.IntegerField(blank=True, db_column='Price', null=True)),
                ('image', models.CharField(blank=True, db_column='Image', max_length=20, null=True)),
                ('marketidx', models.IntegerField(blank=True, db_column='MarketIdx', null=True)),
            ],
            options={
                'db_table': 'Skirt',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Top',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', models.IntegerField(blank=True, db_column='Idx', null=True)),
                ('prodname', models.CharField(blank=True, db_column='ProdName', max_length=20, null=True)),
                ('price', models.IntegerField(blank=True, db_column='Price', null=True)),
                ('image', models.CharField(blank=True, db_column='Image', max_length=20, null=True)),
                ('marketidx', models.IntegerField(blank=True, db_column='MarketIdx', null=True)),
            ],
            options={
                'db_table': 'TOP',
                'managed': False,
            },
        ),
    ]
