# Generated by Django 3.2.11 on 2022-01-08 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qna',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('category', models.CharField(db_column='Category', max_length=20)),
                ('prod_id', models.IntegerField()),
                ('content', models.CharField(db_column='Content', max_length=300)),
            ],
            options={
                'db_table': 'QnA',
                'managed': False,
            },
        ),
    ]
