# Generated by Django 3.2.11 on 2022-01-16 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0002_qna'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('category', models.CharField(max_length=30)),
                ('prod_id', models.IntegerField()),
                ('prod_num', models.IntegerField()),
            ],
            options={
                'db_table': 'Cart',
                'managed': False,
            },
        ),
    ]
