# Generated by Django 3.2.11 on 2022-01-22 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0005_auto_20220122_1936'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategoryitem',
            options={'managed': False},
        ),
    ]
