# Generated by Django 3.2.11 on 2022-01-22 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0007_alter_productcategoryitem_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productcategoryitem',
            table='ProductCategory',
        ),
    ]
