# Generated by Django 3.2.11 on 2022-01-22 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0009_alter_productcategoryitem_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productcategoryitem',
            table=None,
        ),
    ]
