# Generated by Django 4.0.1 on 2022-02-12 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='category_status',
            field=models.CharField(default='ACTIVE', max_length=13),
        ),
    ]
