# Generated by Django 4.0.1 on 2022-01-13 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_detail', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order_detail',
        ),
    ]
