# Generated by Django 4.0.1 on 2022-01-07 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30)),
                ('price', models.PositiveIntegerField(default=0)),
                ('color', models.CharField(choices=[('white', '흰색'), ('black', '검정색'), ('red', '빨간색'), ('green', '초록색'), ('blue', '파란색')], max_length=10)),
                ('size', models.CharField(max_length=1)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('category', models.CharField(choices=[('neat', '니트'), ('hood', '후드'), ('mtm', '맨투맨'), ('shirt', '셔츠')], max_length=5)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='markets.market')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
