# Generated by Django 4.0.1 on 2022-01-08 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoption',
            name='extra_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
