# Generated by Django 4.0.1 on 2022-01-08 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_main_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('main_image_url', models.URLField(max_length=2000)),
                ('seller_name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'product_lists',
                'managed': False,
            },
        ),
    ]
