# Generated by Django 4.0.1 on 2022-02-12 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_alter_market_company_number'),
        ('market_sns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketsns',
            name='market_pk',
            field=models.ForeignKey(db_column='market_fk', on_delete=django.db.models.deletion.CASCADE, related_name='market_sns', to='market.market'),
        ),
    ]
