# Generated by Django 4.0.1 on 2022-01-08 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_productimage_is_main_product_main_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_image_url',
            field=models.URLField(max_length=2000),
        ),
    ]
