# Generated by Django 4.0.1 on 2022-01-21 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_accounttype_user_is_social_master_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='master',
            table='masters',
        ),
    ]
