# Generated by Django 4.0.1 on 2022-01-21 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_master_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='master',
            old_name='account_id',
            new_name='account',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='account_id',
            new_name='account',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='account_id',
            new_name='account',
        ),
    ]
