# Generated by Django 4.0.1 on 2022-01-21 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_account_id_master_account_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='account_type_id',
            new_name='account_type',
        ),
    ]
