# Generated by Django 3.2 on 2022-02-10 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, verbose_name='업체명')),
                ('url', models.TextField(default='', max_length=255, verbose_name='url')),
                ('email', models.TextField(default='', max_length=255, verbose_name='이메일')),
                ('reg_date', models.DateTimeField(auto_now=True, verbose_name='등록일')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='등록일')),
            ],
        ),
    ]
