# Generated by Django 3.2 on 2022-02-09 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='market',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='market',
            name='id',
        ),
        migrations.AddField(
            model_name='market',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.user'),
            preserve_default=False,
        ),
    ]
