# Generated by Django 4.0.1 on 2022-02-11 23:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='market',
            name='email',
        ),
        migrations.AddField(
            model_name='market',
            name='user_fk',
            field=models.ForeignKey(db_column='user_fk', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
