# Generated by Django 4.0.1 on 2022-02-11 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_remove_market_email_market_user_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='market',
            name='contact_number',
        ),
        migrations.AddField(
            model_name='market',
            name='company_number',
            field=models.CharField(default=None, max_length=12, null=True),
        ),
    ]
