# Generated by Django 4.0.1 on 2022-02-12 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_remove_market_contact_number_market_company_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='company_number',
            field=models.CharField(default=None, max_length=12, null=True, unique=True),
        ),
    ]
