# Generated by Django 4.0.1 on 2022-02-12 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_alter_market_company_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='market_status',
            field=models.CharField(default='ACTIVE', max_length=10),
        ),
    ]
