# Generated by Django 4.0.1 on 2022-02-13 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('market', '0005_market_market_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='user_fk',
            field=models.OneToOneField(db_column='user_fk', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
