# Generated by Django 4.0.1 on 2022-01-13 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_user_phone_alter_user_username'),
        ('order', '0002_rename_user_id_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='user.user'),
        ),
    ]
