# Generated by Django 4.0.1 on 2022-02-05 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_delete_shopadmin_shop_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='password',
        ),
        migrations.AddField(
            model_name='shop',
            name='shop_pw',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
