# Generated by Django 3.2.9 on 2022-01-08 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tmp_token',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
