# Generated by Django 3.2.9 on 2022-01-08 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_tmp_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tmp_token',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
