# Generated by Django 3.2 on 2022-01-22 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_seller_user'),
        ('products', '0002_auto_20220121_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemerchandise',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='basemerchandise', to='accounts.seller', verbose_name='셀러'),
        ),
        migrations.AlterField(
            model_name='basemerchandise',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='basemerchandise', to='products.subcategory', verbose_name='서브카테고리'),
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='basemerchandise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='merchandise', to='products.basemerchandise', verbose_name='상품'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='maincategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategory', to='products.maincategory', verbose_name='메인카테고리'),
        ),
    ]
