# Generated by Django 3.2 on 2022-01-16 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_incartitem_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incartitem',
            name='quantitiy',
            field=models.IntegerField(),
        ),
    ]
