# Generated by Django 3.2 on 2022-01-17 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_incartitem_quantitiy'),
    ]

    operations = [
        migrations.AddField(
            model_name='incartitem',
            name='total_price',
            field=models.IntegerField(null=True),
        ),
    ]
