# Generated by Django 3.2 on 2022-01-17 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_incartitem_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incartitem',
            name='total_price',
        ),
    ]
