# Generated by Django 3.2 on 2022-01-14 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='생성날짜')),
                ('updated', models.DateField(auto_now=True, verbose_name='업데이트날짜')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20, verbose_name='상품문의 제목')),
                ('content', models.CharField(max_length=255, verbose_name='상품문의 내용')),
                ('basemerchandise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.basemerchandise', verbose_name='상품')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.customer', verbose_name='유저')),
            ],
            options={
                'verbose_name_plural': '5. 상품문의 목록',
                'db_table': 'questions',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='생성날짜')),
                ('updated', models.DateField(auto_now=True, verbose_name='업데이트날짜')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=255, verbose_name='상품답변 내용')),
                ('basemerchandise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.basemerchandise', verbose_name='상품')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='qna.question', verbose_name='상품문의')),
            ],
            options={
                'verbose_name_plural': '6. 상품답변 목록',
                'db_table': 'answers',
            },
        ),
    ]
