# Generated by Django 4.0.1 on 2022-02-06 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_option', '0003_alter_productoption_inventory_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoption',
            name='add_price',
            field=models.IntegerField(null=True),
        ),
    ]
