# Generated by Django 3.2 on 2022-01-06 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mutbly', '0002_alter_quantity_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quantity',
            name='created_at',
        ),
    ]
