# Generated by Django 3.2 on 2022-02-06 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mutbly', '0007_auto_20220206_0340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='photo',
            field=models.ImageField(default='/media/image/alexi-romano-CCx6Fz_CmOI-unsplash.jpg', upload_to='image'),
        ),
    ]
