# Generated by Django 4.0.1 on 2022-01-19 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('트레이닝', '트레이닝'), ('상의', '상의'), ('기타', '기타'), ('스커트', '스커트'), ('가방', '가방'), ('원피스/세트', '원피스/세트'), ('팬츠', '팬츠'), ('아우터', '아우터'), ('신발', '신발'), ('패션소품', '패션소품'), ('주얼리', '주얼리'), ('언더웨어', '언더웨어')], default='아우터', max_length=80),
        ),
    ]
