# Generated by Django 4.0.1 on 2022-01-19 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('주얼리', '주얼리'), ('기타', '기타'), ('상의', '상의'), ('트레이닝', '트레이닝'), ('가방', '가방'), ('신발', '신발'), ('원피스/세트', '원피스/세트'), ('아우터', '아우터'), ('스커트', '스커트'), ('팬츠', '팬츠'), ('패션소품', '패션소품'), ('언더웨어', '언더웨어')], default='아우터', max_length=80),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(max_length=250, null=True, verbose_name='제품 이미지'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_detail',
            field=models.CharField(max_length=250, null=True, verbose_name='제품 상세이미지'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='히든 상품'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_sold_out',
            field=models.BooleanField(default=False, verbose_name='품절 상품'),
        ),
    ]
