# Generated by Django 3.2 on 2022-01-21 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20220121_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('아우터', '아우터'), ('스커트', '스커트'), ('기타', '기타'), ('상의', '상의'), ('신발', '신발'), ('패션소품', '패션소품'), ('팬츠', '팬츠'), ('트레이닝', '트레이닝'), ('가방', '가방'), ('원피스/세트', '원피스/세트'), ('주얼리', '주얼리'), ('언더웨어', '언더웨어')], default='아우터', max_length=80),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='제품 이미지'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_detail',
            field=models.ImageField(null=True, upload_to='', verbose_name='제품 상세이미지'),
        ),
    ]
