# Generated by Django 4.0.1 on 2022-01-05 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0003_remove_product_image_image_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_img',
            field=models.URLField(blank=True, null=True, unique=True, verbose_name='url'),
        ),
    ]
