# Generated by Django 4.0.1 on 2022-01-05 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0004_product_product_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='brand',
        ),
    ]
