# Generated by Django 4.0.1 on 2022-01-05 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0007_brand_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quantity',
            new_name='stock',
        ),
    ]
