# Generated by Django 4.0.1 on 2022-01-06 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0008_rename_quantity_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='brand_thumb',
            field=models.URLField(blank=True, null=True, unique=True, verbose_name='url'),
        ),
    ]
