# Generated by Django 4.0.1 on 2022-01-09 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_option', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoption',
            name='inventory_Count',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='productoption',
            name='size',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='productoption',
            name='sold_out_yn',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='productoption',
            name='color',
            field=models.CharField(max_length=20),
        ),
    ]
