# Generated by Django 4.0.1 on 2022-02-06 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_option', '0002_productoption_inventory_count_productoption_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoption',
            name='inventory_Count',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
