# Generated by Django 4.0.1 on 2022-02-06 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_product_status'),
        ('product_option', '0004_productoption_add_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoption',
            name='product_pk',
            field=models.ForeignKey(db_column='product_fk', on_delete=django.db.models.deletion.CASCADE, related_name='product_option', to='product.product'),
        ),
    ]
