# Generated by Django 4.0.1 on 2022-01-14 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoption',
            name='add_price',
            field=models.IntegerField(default=0),
        ),
    ]
