# Generated by Django 4.0.1 on 2022-01-07 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('s', 'SMALL'), ('m', 'MEDIUM'), ('l', 'LARGE')], max_length=1),
        ),
    ]
