# Generated by Django 4.0.1 on 2022-01-09 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=45)),
                ('size', models.CharField(max_length=45)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(null=True, upload_to='products')),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
