# Generated by Django 4.0.1 on 2022-01-16 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cartitem',
        ),
    ]
