# Generated by Django 4.0.1 on 2022-01-09 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_board_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='comment',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
