# Generated by Django 3.1.3 on 2022-01-06 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20220105_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoptiongroup',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='쇼핑몰'),
        ),
    ]
