# Generated by Django 3.1.3 on 2022-01-06 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20220106_0138'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoptiongroupitem',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='재고'),
        ),
        migrations.CreateModel(
            name='ProductImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.TextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='쇼핑몰')),
            ],
        ),
    ]
