# Generated by Django 3.1.3 on 2022-01-23 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_product_id_alter_productimg_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoptiongroupitem',
            name='optionItem',
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='productimg',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='productimg',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productImgs', to='product.product'),
        ),
        migrations.AlterField(
            model_name='productoptiongroup',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='productoptiongroup',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optionGroups', to='product.product'),
        ),
        migrations.AlterField(
            model_name='productoptiongroupitem',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='productoptiongroupitem',
            name='productOptionGroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optionItems', to='product.productoptiongroup'),
        ),
        migrations.AlterField(
            model_name='productstock',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='productstock',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productStocks', to='product.product'),
        ),
    ]
