# Generated by Django 4.0.1 on 2022-01-23 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_deleted_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='카테고리 이름'),
        ),
    ]
