# Generated by Django 2.1.15 on 2022-01-06 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20)),
                ('pwd', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=5)),
                ('birth', models.DateField()),
                ('sex', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('email', models.CharField(max_length=60)),
                ('address', models.IntegerField()),
                ('maritial_status', models.IntegerField(blank=True, null=None)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20)),
                ('pwd', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=5)),
                ('birth', models.DateField()),
                ('sex', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('email', models.CharField(max_length=60)),
                ('address', models.IntegerField()),
                ('department_id', models.IntegerField()),
                ('salary', models.IntegerField()),
                ('job_id', models.IntegerField()),
                ('hire_date', models.DateField()),
                ('maritial_status', models.IntegerField(blank=True, null=None)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'employee',
                'managed': False,
            },
        ),
    ]
