# Generated by Django 4.0.1 on 2022-01-08 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('color', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': '색상',
                'verbose_name_plural': '색상',
            },
        ),
        migrations.CreateModel(
            name='size_onepiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('size', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': '사이즈',
                'verbose_name_plural': '사이즈(원피스)',
            },
        ),
        migrations.CreateModel(
            name='size_outer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('size', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': '사이즈',
                'verbose_name_plural': '사이즈(아우터)',
            },
        ),
        migrations.CreateModel(
            name='size_upper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('size', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': '사이즈',
                'verbose_name_plural': '사이즈(상의)',
            },
        ),
    ]
