# Generated by Django 4.0.1 on 2022-01-09 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_board_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='comment',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
