# Generated by Django 4.0.1 on 2022-01-14 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_board_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetail',
            name='detail_image',
        ),
        migrations.RemoveField(
            model_name='productdetail',
            name='main_image',
        ),
        migrations.AddField(
            model_name='product',
            name='detail_image',
            field=models.ImageField(blank=True, null=True, upload_to='detail_image/'),
        ),
        migrations.AddField(
            model_name='product',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='main_image/'),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='is_sold_out',
            field=models.BooleanField(default=False),
        ),
    ]
