# Generated by Django 4.0.1 on 2022-01-14 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_user_email_alter_user_user_id_and_more'),
        ('product', '0005_remove_productdetail_detail_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='CartDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField()),
                ('cart_id', models.ForeignKey(db_column='cart_id', on_delete=django.db.models.deletion.CASCADE, to='product.cart')),
                ('product_detail_id', models.ForeignKey(db_column='product_detail_id', on_delete=django.db.models.deletion.CASCADE, to='product.productdetail')),
                ('product_id', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
