# Generated by Django 4.0.1 on 2022-01-20 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_user_is_social_alter_user_user_email_and_more'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=15)),
                ('product_name', models.CharField(max_length=30)),
                ('product_price', models.IntegerField(default=0)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='main_image/')),
                ('detail_image', models.ImageField(blank=True, null=True, upload_to='detail_image/')),
                ('category', models.ForeignKey(db_column='category', default='None', on_delete=django.db.models.deletion.SET_DEFAULT, to='product.category')),
                ('shop_id', models.ForeignKey(db_column='shop_id', on_delete=django.db.models.deletion.CASCADE, to='shop.shop')),
            ],
        ),
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=20)),
                ('size', models.CharField(max_length=10)),
                ('stock', models.IntegerField()),
                ('is_sold_out', models.BooleanField(default=False)),
                ('product_id', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField()),
                ('option', models.ForeignKey(db_column='product_detail', on_delete=django.db.models.deletion.CASCADE, to='product.productdetail')),
                ('product', models.ForeignKey(db_column='product', on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('user', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='문의', max_length=20)),
                ('content', models.CharField(max_length=200)),
                ('comment', models.CharField(max_length=200, null=True)),
                ('secret', models.BooleanField(default=False)),
                ('date', models.DateTimeField(default=None, null=True)),
                ('comment_date', models.DateTimeField(default=None, null=True)),
                ('product_id', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('user_id', models.ForeignKey(db_column='user_id', default='알 수 없음', on_delete=django.db.models.deletion.SET_DEFAULT, to='user.user')),
            ],
        ),
    ]
