# Generated by Django 4.0.1 on 2022-01-13 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_alter_seller_name'),
        ('product', '0007_alter_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='register',
            new_name='reg_date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('아우터', '아우터'), ('주얼리', '주얼리'), ('가방', '가방'), ('트레이닝', '트레이닝'), ('언더웨어', '언더웨어'), ('스커트', '스커트'), ('팬츠', '팬츠'), ('원피스/세트', '원피스/세트'), ('신발', '신발'), ('패션소품', '패션소품'), ('상의', '상의'), ('기타', '기타')], default='아우터', max_length=80),
        ),
        migrations.AddField(
            model_name='product',
            name='deleted_date',
            field=models.DateTimeField(auto_now=True, verbose_name='삭제 날짜'),
        ),
        migrations.AddField(
            model_name='product',
            name='hit_count',
            field=models.IntegerField(default=0, verbose_name='조회수'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_sold_out',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='like_count',
            field=models.IntegerField(default=0, verbose_name='좋아요수'),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_price',
            field=models.IntegerField(default=0, verbose_name='할인 가격'),
        ),
        migrations.AddField(
            model_name='product',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='등록일'),
        ),
        migrations.AlterField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='seller.seller'),
        ),
        migrations.CreateModel(
            name='Product_options',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reg_date', models.DateTimeField(auto_now=True, verbose_name='등록일')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='등록일')),
                ('opt1_type', models.CharField(max_length=128, verbose_name='옵션1 유형')),
                ('opt1_name', models.CharField(max_length=128, verbose_name='옵션1 유형')),
                ('opt1_price', models.IntegerField(default=0, max_length=128, verbose_name='옵션1 추가가격')),
                ('opt1_stock', models.IntegerField(max_length=128, verbose_name='옵션1 재고수량')),
                ('opt2_type', models.CharField(max_length=128, verbose_name='옵션2 유형')),
                ('opt2_name', models.CharField(max_length=128, verbose_name='옵션2 유형')),
                ('opt2_price', models.IntegerField(default=0, max_length=128, verbose_name='옵션2 추가가격')),
                ('opt2_stock', models.IntegerField(max_length=128, verbose_name='옵션2 재고수량')),
                ('opt3_type', models.CharField(max_length=128, verbose_name='옵션3 유형')),
                ('opt3_name', models.CharField(max_length=128, verbose_name='옵션3 유형')),
                ('opt3_price', models.IntegerField(default=0, max_length=128, verbose_name='옵션3 추가가격')),
                ('opt3_stock', models.IntegerField(max_length=128, verbose_name='옵션3 재고수량')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_options', to='product.product')),
            ],
        ),
    ]
