# Generated by Django 3.2.9 on 2022-01-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_product_option_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_option',
            name='size',
            field=models.CharField(max_length=200, null=True, verbose_name='사이즈'),
        ),
    ]
