# Generated by Django 4.0.1 on 2022-01-13 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('상의', '상의'), ('언더웨어', '언더웨어'), ('아우터', '아우터'), ('스커트', '스커트'), ('기타', '기타'), ('팬츠', '팬츠'), ('신발', '신발'), ('주얼리', '주얼리'), ('트레이닝', '트레이닝'), ('가방', '가방'), ('패션소품', '패션소품'), ('원피스/세트', '원피스/세트')], default='아우터', max_length=80),
        ),
        migrations.AlterField(
            model_name='product_options',
            name='opt1_price',
            field=models.IntegerField(default=0, verbose_name='옵션1 추가가격'),
        ),
        migrations.AlterField(
            model_name='product_options',
            name='opt1_stock',
            field=models.IntegerField(verbose_name='옵션1 재고수량'),
        ),
        migrations.AlterField(
            model_name='product_options',
            name='opt2_price',
            field=models.IntegerField(default=0, verbose_name='옵션2 추가가격'),
        ),
        migrations.AlterField(
            model_name='product_options',
            name='opt2_stock',
            field=models.IntegerField(verbose_name='옵션2 재고수량'),
        ),
        migrations.AlterField(
            model_name='product_options',
            name='opt3_price',
            field=models.IntegerField(default=0, verbose_name='옵션3 추가가격'),
        ),
        migrations.AlterField(
            model_name='product_options',
            name='opt3_stock',
            field=models.IntegerField(verbose_name='옵션3 재고수량'),
        ),
    ]
