# Generated by Django 4.0.1 on 2022-01-14 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_detail',
            field=models.ImageField(null=True, upload_to='', verbose_name='제품 상세이미지'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('상의', '상의'), ('기타', '기타'), ('팬츠', '팬츠'), ('가방', '가방'), ('원피스/세트', '원피스/세트'), ('언더웨어', '언더웨어'), ('트레이닝', '트레이닝'), ('주얼리', '주얼리'), ('신발', '신발'), ('아우터', '아우터'), ('스커트', '스커트'), ('패션소품', '패션소품')], default='아우터', max_length=80),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='제품 이미지'),
        ),
    ]
