# Generated by Django 4.0.1 on 2022-01-14 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_remove_product_count_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('가방', '가방'), ('원피스/세트', '원피스/세트'), ('기타', '기타'), ('트레이닝', '트레이닝'), ('신발', '신발'), ('상의', '상의'), ('팬츠', '팬츠'), ('패션소품', '패션소품'), ('스커트', '스커트'), ('아우터', '아우터'), ('언더웨어', '언더웨어'), ('주얼리', '주얼리')], default='아우터', max_length=80),
        ),
        migrations.AlterField(
            model_name='product_options',
            name='opt2_type',
            field=models.CharField(max_length=128, null=True, verbose_name='옵션2 유형'),
        ),
        migrations.AlterField(
            model_name='product_options',
            name='opt3_price',
            field=models.IntegerField(default=0, null=True, verbose_name='옵션3 추가가격'),
        ),
        migrations.AlterField(
            model_name='product_options',
            name='opt3_stock',
            field=models.IntegerField(null=True, verbose_name='옵션3 재고수량'),
        ),
    ]
