# Generated by Django 4.0.1 on 2022-01-14 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('스커트', '스커트'), ('가방', '가방'), ('아우터', '아우터'), ('주얼리', '주얼리'), ('기타', '기타'), ('원피스/세트', '원피스/세트'), ('트레이닝', '트레이닝'), ('신발', '신발'), ('팬츠', '팬츠'), ('언더웨어', '언더웨어'), ('패션소품', '패션소품'), ('상의', '상의')], default='아우터', max_length=80),
        ),
        migrations.AlterField(
            model_name='product_options',
            name='opt1_name',
            field=models.CharField(max_length=128, verbose_name='옵션1 이름'),
        ),
        migrations.AlterField(
            model_name='product_options',
            name='opt2_name',
            field=models.CharField(default=None, max_length=128, null=True, verbose_name='옵션2 유형'),
        ),
        migrations.AlterField(
            model_name='product_options',
            name='opt2_price',
            field=models.IntegerField(default=None, null=True, verbose_name='옵션2 추가가격'),
        ),
        migrations.AlterField(
            model_name='product_options',
            name='opt2_stock',
            field=models.IntegerField(default=None, null=True, verbose_name='옵션2 재고수량'),
        ),
        migrations.AlterField(
            model_name='product_options',
            name='opt2_type',
            field=models.CharField(default=None, max_length=128, null=True, verbose_name='옵션2 유형'),
        ),
        migrations.AlterField(
            model_name='product_options',
            name='opt3_name',
            field=models.CharField(default=None, max_length=128, null=True, verbose_name='옵션3 유형'),
        ),
        migrations.AlterField(
            model_name='product_options',
            name='opt3_price',
            field=models.IntegerField(default=None, null=True, verbose_name='옵션3 추가가격'),
        ),
        migrations.AlterField(
            model_name='product_options',
            name='opt3_stock',
            field=models.IntegerField(default=None, null=True, verbose_name='옵션3 재고수량'),
        ),
        migrations.AlterField(
            model_name='product_options',
            name='opt3_type',
            field=models.CharField(default=None, max_length=128, null=True, verbose_name='옵션3 유형'),
        ),
    ]
