# Generated by Django 4.0.1 on 2022-01-14 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('아우터', '아우터'), ('주얼리', '주얼리'), ('기타', '기타'), ('언더웨어', '언더웨어'), ('가방', '가방'), ('팬츠', '팬츠'), ('상의', '상의'), ('트레이닝', '트레이닝'), ('패션소품', '패션소품'), ('원피스/세트', '원피스/세트'), ('스커트', '스커트'), ('신발', '신발')], default='아우터', max_length=80),
        ),
    ]
