# Generated by Django 4.0.1 on 2022-01-14 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('언더웨어', '언더웨어'), ('주얼리', '주얼리'), ('패션소품', '패션소품'), ('가방', '가방'), ('팬츠', '팬츠'), ('상의', '상의'), ('원피스/세트', '원피스/세트'), ('신발', '신발'), ('기타', '기타'), ('아우터', '아우터'), ('트레이닝', '트레이닝'), ('스커트', '스커트')], default='아우터', max_length=80),
        ),
    ]
