# Generated by Django 4.0.1 on 2022-01-14 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cart',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('원피스/세트', '원피스/세트'), ('주얼리', '주얼리'), ('스커트', '스커트'), ('가방', '가방'), ('상의', '상의'), ('신발', '신발'), ('트레이닝', '트레이닝'), ('기타', '기타'), ('팬츠', '팬츠'), ('패션소품', '패션소품'), ('아우터', '아우터'), ('언더웨어', '언더웨어')], default='아우터', max_length=80),
        ),
    ]
