# Generated by Django 4.0.1 on 2022-01-15 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('패션소품', '패션소품'), ('아우터', '아우터'), ('팬츠', '팬츠'), ('신발', '신발'), ('가방', '가방'), ('트레이닝', '트레이닝'), ('언더웨어', '언더웨어'), ('상의', '상의'), ('스커트', '스커트'), ('주얼리', '주얼리'), ('기타', '기타'), ('원피스/세트', '원피스/세트')], default='아우터', max_length=80),
        ),
    ]
