# Generated by Django 4.0.1 on 2022-01-06 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product_qna',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=255, verbose_name='질문내용')),
                ('datetime', models.DateTimeField(auto_now=True, verbose_name='등록일')),
            ],
        ),
    ]
