# Generated by Django 4.0.1 on 2022-01-06 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0002_product_qna_product_product_qna_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_qna',
            name='content',
            field=models.TextField(max_length=255, verbose_name='질문내용'),
        ),
    ]
