# Generated by Django 3.2 on 2022-02-10 11:13

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='갱신일')),
                ('name', models.CharField(max_length=100, verbose_name='이름')),
                ('gender', models.CharField(blank=True, choices=[('M', '남성'), ('F', '여성')], max_length=1, verbose_name='성별')),
                ('profile_img', models.ImageField(blank=True, null=True, upload_to='accounts/profile_img/%Y/%m/%d', verbose_name='프로필')),
                ('age_range', models.CharField(max_length=100, verbose_name='연령대')),
                ('provider_type_code', models.CharField(choices=[('local', '로컬'), ('kakao', '카카오')], default='local', max_length=20, verbose_name='프로바이더 타입코드')),
                ('provider_accounts_id', models.PositiveIntegerField(default=0, verbose_name='프로바이더 회원번호')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='User_recommand',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='갱신일')),
                ('keyword1', models.CharField(max_length=128, verbose_name='키워드1')),
                ('keyword2', models.CharField(max_length=128, verbose_name='키워드2')),
                ('keyword3', models.CharField(max_length=128, verbose_name='키워드3')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_recommand', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
