# Generated by Django 4.0.1 on 2022-01-06 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_email',
            field=models.EmailField(max_length=128, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(max_length=20, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_pw',
            field=models.TextField(max_length=500, verbose_name=''),
        ),
    ]
