# Generated by Django 3.2 on 2022-02-09 07:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='accounts/profile_img/%Y/%m/%d', verbose_name='프로필'),
        ),
        migrations.AlterField(
            model_name='user',
            name='reg_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='등록일'),
        ),
        migrations.AlterField(
            model_name='user',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='갱신일'),
        ),
        migrations.CreateModel(
            name='User_recommand',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='갱신일')),
                ('keyword1', models.CharField(max_length=128, verbose_name='키워드1')),
                ('keyword2', models.CharField(max_length=128, verbose_name='키워드2')),
                ('keyword3', models.CharField(max_length=128, verbose_name='키워드3')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_recommand', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
