# Generated by Django 4.0.1 on 2022-02-04 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_product_main_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoption',
            name='stock',
            field=models.IntegerField(null=True),
        ),
    ]
