# Generated by Django 4.0.1 on 2022-01-06 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=128, verbose_name='핸드폰 번호'),
        ),
    ]
