# Generated by Django 4.0.1 on 2022-01-13 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0008_remove_user_phone_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deliver',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('zipcode', models.TextField(max_length=255, verbose_name='우편번호')),
                ('address', models.TextField(max_length=255, verbose_name='주소')),
                ('adrress_detail', models.TextField(max_length=255, verbose_name='상세주소')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliver', to='user.user')),
            ],
        ),
    ]
