# Generated by Django 4.0.1 on 2022-01-07 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='', max_length=128, verbose_name='유저이름'),
        ),
    ]
