# Generated by Django 4.0.1 on 2022-01-07 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=128, verbose_name='유저이름'),
        ),
    ]
