# Generated by Django 4.0.1 on 2022-01-14 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_user_options_alter_user_managers_user_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='', max_length=128, verbose_name='아이디')),
                ('name', models.CharField(default='', max_length=128, verbose_name='유저 이름')),
                ('password', models.CharField(max_length=128, verbose_name='비밀번호')),
                ('email', models.CharField(max_length=128, verbose_name='이메일')),
            ],
        ),
    ]
