# Generated by Django 4.0.1 on 2022-01-14 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_remove_cart_id_alter_cart_user'),
        ('order', '0004_order_detail'),
        ('qna', '0006_alter_product_qna_product_alter_product_qna_user'),
        ('deliver', '0001_initial'),
        ('user', '0012_delete_account_alter_user_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Account',
        ),
    ]
