# Generated by Django 4.0.1 on 2022-01-23 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='site_url',
            field=models.URLField(max_length=150, unique=True, verbose_name='마켓 URL'),
        ),
    ]
