# Generated by Django 3.1.3 on 2022-01-07 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_remove_question_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='product',
        ),
    ]
