# Generated by Django 3.2 on 2022-02-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_category'),
        ('cart', '0003_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='product_option',
            field=models.ManyToManyField(blank=True, related_name='cart', to='product.Product_option'),
        ),
    ]
