# Generated by Django 3.2 on 2022-02-10 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_category'),
        ('cart', '0004_cart_product_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
        migrations.AddField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='product.product'),
        ),
        migrations.RemoveField(
            model_name='cart',
            name='product_option',
        ),
        migrations.AddField(
            model_name='cart',
            name='product_option',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='product.product_option'),
        ),
    ]
