# Generated by Django 3.2 on 2022-01-17 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_remove_incartitem_total_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incartitem',
            old_name='quantitiy',
            new_name='quantity',
        ),
    ]
