# Generated by Django 3.2 on 2022-02-10 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('가방', '가방'), ('패션소품', '패션소품'), ('신발', '신발'), ('기타', '기타'), ('스커트', '스커트'), ('상의', '상의'), ('팬츠', '팬츠'), ('원피스/세트', '원피스/세트'), ('주얼리', '주얼리'), ('언더웨어', '언더웨어'), ('트레이닝', '트레이닝'), ('아우터', '아우터')], default='아우터', max_length=80)),
                ('name', models.CharField(max_length=128, verbose_name='제품명')),
                ('price', models.IntegerField(default=0, verbose_name='가격')),
                ('sale_price', models.IntegerField(default=0, verbose_name='할인 가격')),
                ('description', models.TextField(max_length=255, verbose_name='제품설명')),
                ('image', models.ImageField(null=True, upload_to='', verbose_name='제품 이미지')),
                ('image_detail', models.ImageField(null=True, upload_to='', verbose_name='제품 상세이미지')),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_hidden', models.BooleanField(default=False, verbose_name='히든 상품')),
                ('is_sold_out', models.BooleanField(default=False, verbose_name='품절 상품')),
                ('hit_count', models.IntegerField(default=0, verbose_name='조회수')),
                ('like_count', models.IntegerField(default=0, verbose_name='좋아요수')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='업데이트일')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='갱신일')),
            ],
        ),
        migrations.CreateModel(
            name='Product_option',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reg_date', models.DateTimeField(auto_now=True, verbose_name='등록일')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='등록일')),
                ('opt1_type', models.CharField(max_length=128, verbose_name='옵션1 유형')),
                ('opt1_name', models.CharField(max_length=128, verbose_name='옵션1 이름')),
                ('opt1_price', models.IntegerField(default=0, verbose_name='옵션1 추가가격')),
                ('opt1_stock', models.IntegerField(verbose_name='옵션1 재고수량')),
                ('opt2_type', models.CharField(default=None, max_length=128, null=True, verbose_name='옵션2 유형')),
                ('opt2_name', models.CharField(default=None, max_length=128, null=True, verbose_name='옵션2 유형')),
                ('opt2_price', models.IntegerField(default=None, null=True, verbose_name='옵션2 추가가격')),
                ('opt2_stock', models.IntegerField(default=None, null=True, verbose_name='옵션2 재고수량')),
            ],
        ),
        migrations.CreateModel(
            name='Product_qna',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=128, verbose_name='질문제목')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='갱신날짜')),
                ('content', models.TextField(max_length=255, verbose_name='질문내용')),
                ('product', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='products_feature', to='product.product')),
            ],
        ),
    ]
