# Generated by Django 3.2 on 2022-02-09 07:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='deleted_date',
        ),
        migrations.AddField(
            model_name='product',
            name='cart',
            field=models.ManyToManyField(blank=True, related_name='carts', to='cart.Cart'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('가방', '가방'), ('원피스/세트', '원피스/세트'), ('주얼리', '주얼리'), ('트레이닝', '트레이닝'), ('아우터', '아우터'), ('기타', '기타'), ('상의', '상의'), ('스커트', '스커트'), ('신발', '신발'), ('패션소품', '패션소품'), ('팬츠', '팬츠'), ('언더웨어', '언더웨어')], default='아우터', max_length=80),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='히든 상품'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_sold_out',
            field=models.BooleanField(default=False, verbose_name='품절 상품'),
        ),
        migrations.AlterField(
            model_name='product',
            name='reg_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='업데이트일'),
        ),
        migrations.AlterField(
            model_name='product',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='갱신일'),
        ),
        migrations.CreateModel(
            name='Product_qna',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=128, verbose_name='질문제목')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='갱신날짜')),
                ('content', models.TextField(max_length=255, verbose_name='질문내용')),
                ('datetime', models.DateTimeField(auto_now=True, verbose_name='작성일')),
                ('product', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='products_feature', to='product.product')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='users_feature', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
