# Generated by Django 3.2 on 2022-02-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('주얼리', '주얼리'), ('팬츠', '팬츠'), ('아우터', '아우터'), ('스커트', '스커트'), ('신발', '신발'), ('패션소품', '패션소품'), ('기타', '기타'), ('가방', '가방'), ('트레이닝', '트레이닝'), ('상의', '상의'), ('언더웨어', '언더웨어'), ('원피스/세트', '원피스/세트')], default='아우터', max_length=80),
        ),
    ]
