# Generated by Django 3.2.9 on 2022-02-09 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20220209_0645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='productoption',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product_option',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='product.productoption', verbose_name='구매상품의 옵션'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.product', verbose_name='구매상품'),
        ),
    ]
