# Generated by Django 3.2 on 2022-02-11 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('트레이닝', '트레이닝'), ('원피스/세트', '원피스/세트'), ('기타', '기타'), ('팬츠', '팬츠'), ('가방', '가방'), ('스커트', '스커트'), ('상의', '상의'), ('주얼리', '주얼리'), ('아우터', '아우터'), ('신발', '신발'), ('패션소품', '패션소품'), ('언더웨어', '언더웨어')], default='아우터', max_length=80),
        ),
    ]
