# Generated by Django 3.2.9 on 2022-02-09 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20220209_0656'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='product_option',
            new_name='productoption',
        ),
    ]
