# Generated by Django 3.2.9 on 2022-02-09 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_rename_product_option_cartitem_productoption'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='product_option',
            new_name='productoption',
        ),
    ]
