# Generated by Django 4.0.1 on 2022-02-05 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetail',
            name='product_id',
            field=models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='options', to='product.product'),
        ),
    ]
