# Generated by Django 3.2.9 on 2022-02-11 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20220209_0939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='productoption',
            new_name='product_option',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='productoption',
            new_name='product_option',
        ),
    ]
