# Generated by Django 4.0.1 on 2022-01-14 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_remove_product_cart_alter_product_category'),
        ('cart', '0002_remove_cart_id_alter_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='product',
            field=models.ManyToManyField(blank=True, null=True, related_name='cart', to='product.Product'),
        ),
    ]
