# Generated by Django 4.0.1 on 2022-01-15 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='cartItem',
        ),
    ]
