# Generated by Django 3.2 on 2022-01-21 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_category_alter_product_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='deleted_date',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('팬츠', '팬츠'), ('언더웨어', '언더웨어'), ('트레이닝', '트레이닝'), ('패션소품', '패션소품'), ('기타', '기타'), ('가방', '가방'), ('주얼리', '주얼리'), ('상의', '상의'), ('원피스/세트', '원피스/세트'), ('신발', '신발'), ('아우터', '아우터'), ('스커트', '스커트')], default='아우터', max_length=80),
        ),
        migrations.AlterField(
            model_name='product',
            name='reg_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='업데이트일'),
        ),
        migrations.AlterField(
            model_name='product',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='갱신일'),
        ),
    ]
