# Generated by Django 3.2 on 2022-02-02 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20220121_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('신발', '신발'), ('트레이닝', '트레이닝'), ('스커트', '스커트'), ('패션소품', '패션소품'), ('가방', '가방'), ('언더웨어', '언더웨어'), ('기타', '기타'), ('주얼리', '주얼리'), ('상의', '상의'), ('팬츠', '팬츠'), ('원피스/세트', '원피스/세트'), ('아우터', '아우터')], default='아우터', max_length=80),
        ),
    ]
