# Generated by Django 3.2 on 2022-02-02 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('원피스/세트', '원피스/세트'), ('신발', '신발'), ('아우터', '아우터'), ('스커트', '스커트'), ('패션소품', '패션소품'), ('팬츠', '팬츠'), ('언더웨어', '언더웨어'), ('가방', '가방'), ('기타', '기타'), ('트레이닝', '트레이닝'), ('주얼리', '주얼리'), ('상의', '상의')], default='아우터', max_length=80),
        ),
    ]
