# Generated by Django 3.2.9 on 2022-01-12 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_option_shopping_basket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_option',
            name='shopping_basket',
        ),
        migrations.AddField(
            model_name='product',
            name='shopping_basket',
            field=models.ManyToManyField(to='product.Product'),
        ),
    ]
