# Generated by Django 4.0.1 on 2022-02-02 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_market_id_user_market_yn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refreshstorage',
            name='refresh_token',
            field=models.CharField(max_length=500),
        ),
    ]
