# Generated by Django 4.0 on 2022-01-08 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MallsItems',
            fields=[
                ('num', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('price', models.PositiveIntegerField()),
                ('useyn', models.CharField(max_length=50)),
                ('kind', models.CharField(blank=True, max_length=1, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('image_url', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('regdate', models.DateField()),
            ],
            options={
                'db_table': 'malls_items',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MallsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop', models.CharField(max_length=80)),
                ('kind', models.CharField(blank=True, max_length=80, null=True)),
                ('date', models.DateField()),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('url', models.CharField(max_length=200)),
                ('img_url', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'malls_list',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MallsQuestion',
            fields=[
                ('q_num', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=30)),
                ('content', models.CharField(max_length=1000)),
                ('reply', models.CharField(blank=True, max_length=1000, null=True)),
                ('rep', models.CharField(max_length=1)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
            options={
                'db_table': 'malls_question',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
