# Generated by Django 3.2 on 2022-01-14 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseMerchandise',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('common_code', models.CharField(max_length=8, verbose_name='상품 공통코드')),
                ('name', models.CharField(max_length=20, verbose_name='상품명')),
                ('standard_price', models.PositiveIntegerField(default=0, verbose_name='상품 정가')),
                ('discounted_price', models.PositiveIntegerField(default=0, verbose_name='상품 할인금액')),
                ('main_img', models.URLField(blank=True, null=True, verbose_name='상품 메인이미지')),
                ('sub_img_0', models.URLField(blank=True, null=True, verbose_name='상품 서브이미지0')),
                ('sub_img_1', models.URLField(blank=True, null=True, verbose_name='상품 서브이미지1')),
                ('sub_img_2', models.URLField(blank=True, null=True, verbose_name='상품 서브이미지2')),
                ('description', models.TextField(blank=True, null=True, verbose_name='상품 설명')),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.seller', verbose_name='셀러')),
            ],
            options={
                'verbose_name_plural': '3. 상품 목록',
                'db_table': 'basemerchandises',
            },
        ),
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='생성날짜')),
                ('updated', models.DateField(auto_now=True, verbose_name='업데이트날짜')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, verbose_name='메인카테고리')),
            ],
            options={
                'verbose_name_plural': '1. 메인카테고리 목록',
                'db_table': 'maincategories',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='생성날짜')),
                ('updated', models.DateField(auto_now=True, verbose_name='업데이트날짜')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, verbose_name='서브카테고리')),
                ('maincategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.maincategory', verbose_name='메인카테고리')),
            ],
            options={
                'verbose_name_plural': '2. 서브카테고리 목록',
                'db_table': 'subcategories',
            },
        ),
        migrations.CreateModel(
            name='Merchandise',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='생성날짜')),
                ('updated', models.DateField(auto_now=True, verbose_name='업데이트날짜')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_code', models.CharField(max_length=12, unique=True, verbose_name='옵션상품 전체코드')),
                ('color', models.CharField(max_length=20, verbose_name='옵션상품 색상')),
                ('size', models.CharField(choices=[('FREE', 'FREE'), ('SMALL', 'S'), ('MEDIUM', 'M'), ('LARGE', 'L'), ('XLARGE', 'XL')], max_length=6, verbose_name='옵션상품 사이즈')),
                ('current_stock', models.PositiveIntegerField(default=0, verbose_name='옵션상품 현재재고')),
                ('safety_stock', models.PositiveIntegerField(default=0, verbose_name='옵션상품 안전재고')),
                ('soldout_state', models.CharField(choices=[('IN', 'INSTOCK'), ('TEM', 'TEMPORARY_SOLDOUT'), ('PER', 'PERMANANT_SOLDOUT')], max_length=3, verbose_name='옵션상품 품절상태')),
                ('on_sale', models.BooleanField(default=True, verbose_name='상품 판매')),
                ('on_display', models.BooleanField(default=True, verbose_name='상품 전시')),
                ('basemerchandise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.basemerchandise', verbose_name='상품')),
            ],
            options={
                'verbose_name_plural': '4. 옵션상품 목록',
                'db_table': 'merchandises',
            },
        ),
        migrations.AddField(
            model_name='basemerchandise',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.subcategory', verbose_name='서브카테고리'),
        ),
    ]
