# Generated by Django 3.2 on 2022-01-21 23:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basemerchandise',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='생성날짜'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='basemerchandise',
            name='updated',
            field=models.DateField(auto_now=True, verbose_name='업데이트날짜'),
        ),
    ]
