# Generated by Django 3.2.9 on 2022-01-07 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='상품명')),
                ('price', models.IntegerField(verbose_name='가격')),
                ('size', models.CharField(max_length=200, null=True, verbose_name='사이즈')),
                ('count', models.IntegerField(verbose_name='재고')),
                ('description', models.TextField(max_length=200, verbose_name='설명')),
                ('image', models.ImageField(null=True, upload_to='product/', verbose_name='사진')),
                ('seller', models.CharField(max_length=200, null=True, verbose_name='입점사')),
            ],
        ),
    ]
