# Generated by Django 3.2.9 on 2022-01-12 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(default=1, max_length=100, verbose_name='색상'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(default=1, max_length=200, verbose_name='사이즈'),
            preserve_default=False,
        ),
    ]
