# Generated by Django 3.2.9 on 2022-01-12 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_product_option_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='shopping_basket',
        ),
    ]
