# Generated by Django 3.2.9 on 2022-01-12 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_remove_product_shopping_basket'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product_option',
            new_name='Productreal',
        ),
    ]
