# Generated by Django 4.0.1 on 2022-02-03 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_seller_reg_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='address',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='market',
            field=models.CharField(default='', max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
