# Generated by Django 4.0.1 on 2022-02-13 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0003_alter_productcategory_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketDailySales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('sales', models.PositiveIntegerField(default=0)),
                ('sales_num', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('-date', 'sales'),
            },
        ),
        migrations.CreateModel(
            name='ProductDailySales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('sales', models.PositiveIntegerField(default=0)),
                ('sales_num', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.product')),
            ],
            options={
                'ordering': ('-date', 'sales'),
            },
        ),
    ]
