# Generated by Django 4.0.1 on 2022-01-23 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_cartitemlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producthistory',
            name='discount_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
