# Generated by Django 4.0.1 on 2022-01-08 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='board',
            name='private_yn',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='board',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='board',
            name='type',
            field=models.CharField(default='', max_length=15),
        ),
    ]
