# Generated by Django 3.1.3 on 2022-01-06 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lionuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lionuser',
            name='password',
            field=models.TextField(),
        ),
    ]
