# Generated by Django 3.1.3 on 2022-01-06 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lionuser', '0002_auto_20220106_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lionuser',
            name='password',
            field=models.CharField(max_length=30),
        ),
    ]
