# Generated by Django 3.1.3 on 2022-01-06 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lionuser', '0003_auto_20220106_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lionuser',
            name='password',
            field=models.TextField(),
        ),
    ]
