# Generated by Django 3.1.3 on 2022-01-06 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lionuser', '0004_auto_20220106_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='lionuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
