# Generated by Django 3.1.3 on 2022-01-06 14:41

from django.db import migrations
import lionuser.models


class Migration(migrations.Migration):

    dependencies = [
        ('lionuser', '0006_auto_20220106_1431'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='lionuser',
            managers=[
                ('objects', lionuser.models.LionuserManager()),
            ],
        ),
    ]
