# Generated by Django 3.1.3 on 2022-01-06 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lionuser', '0007_auto_20220106_1441'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lionuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
