# Generated by Django 3.2 on 2022-01-15 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name_plural': '2. 상품답변 목록'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name_plural': '1. 상품문의 목록'},
        ),
    ]
