# Generated by Django 4.0.1 on 2022-02-04 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShopAdmin',
        ),
        migrations.AddField(
            model_name='shop',
            name='password',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
