# Generated by Django 4.0.1 on 2022-02-13 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
    ]
