# Generated by Django 4.0.1 on 2022-01-06 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100)),
                ('file_path', models.CharField(max_length=150)),
                ('file_type', models.CharField(max_length=25)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
