# Generated by Django 4.0.1 on 2022-02-10 06:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProductPaymentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.PositiveIntegerField(verbose_name='구매 물품 총액(비과세 포함)')),
                ('tax_free_amount', models.PositiveIntegerField(verbose_name='상품 비과세 금액')),
                ('vat_amount', models.PositiveIntegerField(verbose_name='상품 부가세 금액')),
                ('tid', models.PositiveIntegerField(verbose_name='결제번호')),
                ('status', models.CharField(blank=True, choices=[('C', '완료'), ('W', '대기'), ('F', '실패')], max_length=20, verbose_name='결제상태')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProductPaymentApprovalResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid', models.PositiveIntegerField(verbose_name='요청번호')),
                ('total_amount', models.PositiveIntegerField(verbose_name='결제금액')),
                ('product_name', models.CharField(max_length=100, verbose_name='상품 이름')),
                ('payment_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.userproductpaymentrequest')),
            ],
        ),
    ]
