# Generated by Django 4.0.1 on 2022-01-09 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='detailImage',
            field=models.ImageField(blank=True, null=True, upload_to='product/'),
        ),
    ]
