# Generated by Django 3.2 on 2022-01-16 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incartitem',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
