# Generated by Django 4.0.1 on 2022-01-05 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0005_remove_category_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=100, null=True, unique=True),
        ),
    ]
