# Generated by Django 4.0.1 on 2022-01-15 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id_cart', models.CharField(db_column='id_Cart', max_length=5, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Cart',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cartitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
            ],
            options={
                'db_table': 'CartItem',
                'managed': False,
            },
        ),
    ]
