# Generated by Django 4.0.1 on 2022-01-13 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_product_category'),
        ('user', '0008_remove_user_phone_alter_user_username'),
        ('qna', '0004_product_qna_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_qna',
            name='datetime',
        ),
        migrations.AddField(
            model_name='product_qna',
            name='reg_date',
            field=models.DateTimeField(auto_now=True, verbose_name='등록일'),
        ),
        migrations.AddField(
            model_name='product_qna',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='등록일'),
        ),
        migrations.AlterField(
            model_name='product_qna',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='product_qna', to='product.product'),
        ),
        migrations.AlterField(
            model_name='product_qna',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='product_qna', to='user.user'),
        ),
    ]
