# Generated by Django 4.0.1 on 2022-01-13 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_user_phone_alter_user_username'),
        ('product', '0011_alter_product_category_and_more'),
        ('qna', '0005_remove_product_qna_datetime_product_qna_reg_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_qna',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_qna', to='product.product'),
        ),
        migrations.AlterField(
            model_name='product_qna',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_qna', to='user.user'),
        ),
    ]
