# Generated by Django 3.2 on 2022-02-02 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_alter_market_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='market',
            old_name='id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='market',
            name='admin',
        ),
    ]
